import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("weather_data.csv")
data["Temperature"] = pd.to_numeric(data["Temperature"])
data["Humidity"] = pd.to_numeric(data["Humidity"])
data["Rainfall"] = pd.to_numeric(data["Rainfall"])
avg_temp = np.mean(data["Temperature"])
max_temp = np.max(data["Temperature"])
min_temp = np.min(data["Temperature"])
print("Average Temperature:", avg_temp)
print("Maximum Temperature:", max_temp)
print("Minimum Temperature:", min_temp)
plt.figure()
plt.plot(data["Day"], data["Temperature"], marker="o")
plt.title("Daily Temperature Trend")
plt.xlabel("Day")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.show()
plt.figure()
plt.bar(data["Day"], data["Humidity"])
plt.title("Daily Humidity Levels")
plt.xlabel("Day")
plt.ylabel("Humidity (%)")
plt.show()
plt.figure()
plt.scatter(data["Temperature"], data["Rainfall"], s=200)
plt.title("Temperature vs Rainfall")
plt.xlabel("Temperature (°C)")
plt.ylabel("Rainfall (mm)")
plt.show()
